"""Branding constants for the public CIMA Demonstrator surface."""
from __future__ import annotations

PUBLIC_PROJECT_NAME = "CIMA Demonstrator"
PUBLIC_PROJECT_SLUG = "cima_demo"
PUBLIC_MODEL_ID = PUBLIC_PROJECT_SLUG
PUBLIC_OWNER = PUBLIC_PROJECT_SLUG
PUBLIC_DOCS_PATH = f"/{PUBLIC_PROJECT_SLUG}/docs"
PUBLIC_CHAT_PATH = f"/{PUBLIC_PROJECT_SLUG}/chat"
PUBLIC_CONVERSATIONS_PREFIX = f"/{PUBLIC_PROJECT_SLUG}/conversations"
PUBLIC_EVENTBUS_TOPIC = f"{PUBLIC_PROJECT_SLUG}.domain_events"
PUBLIC_WORKSPACE_DIR = f"/var/{PUBLIC_PROJECT_SLUG}/workspace"

PUBLIC_HANDOFF_PREFIX = f"/{PUBLIC_PROJECT_SLUG}/handoff"

PUBLIC_CONTEXT_PREFIX = f"/{PUBLIC_PROJECT_SLUG}/context"
PUBLIC_RUNS_PREFIX = f"/{PUBLIC_PROJECT_SLUG}/runs"
